-- PageRadar initial schema. This migration is additive and creates no Supabase project resources.
CREATE TYPE "ChangeType" AS ENUM ('DEADLINE_CHANGED', 'ELIGIBILITY_CHANGED', 'STATUS_CHANGED', 'REQUIREMENT_CHANGED', 'PRICE_CHANGED', 'LINK_CHANGED', 'SECTION_CHANGED', 'CONTENT_CHANGED');
CREATE TYPE "InterestType" AS ENUM ('DEADLINE', 'ELIGIBILITY', 'STATUS', 'REQUIREMENT', 'PRICE', 'LINK');
CREATE TYPE "NotificationChannel" AS ENUM ('EMAIL');
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED');
CREATE TYPE "CheckRunStatus" AS ENUM ('QUEUED', 'RUNNING', 'SUCCESS', 'NO_CHANGE', 'CHANGE_DETECTED', 'FAILED');
CREATE TABLE "User" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Watch" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "url" TEXT NOT NULL, "title" TEXT NOT NULL, "checkInterval" INTEGER NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "lastCheckedAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ NOT NULL, CONSTRAINT "Watch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Snapshot" ("id" UUID NOT NULL, "watchId" UUID NOT NULL, "content" TEXT NOT NULL, "contentHash" TEXT NOT NULL, "capturedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Snapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Change" ("id" UUID NOT NULL, "watchId" UUID NOT NULL, "oldSnapshotId" UUID, "newSnapshotId" UUID, "type" "ChangeType" NOT NULL, "oldValue" TEXT, "newValue" TEXT, "section" TEXT, "importance" INTEGER NOT NULL DEFAULT 0, "reason" TEXT, "detectedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Change_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserInterest" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "type" "InterestType" NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, CONSTRAINT "UserInterest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "changeId" UUID, "channel" "NotificationChannel" NOT NULL DEFAULT 'EMAIL', "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING', "message" TEXT NOT NULL, "sentAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CheckRun" ("id" UUID NOT NULL, "watchId" UUID NOT NULL, "status" "CheckRunStatus" NOT NULL DEFAULT 'QUEUED', "startedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMPTZ, "error" TEXT, CONSTRAINT "CheckRun_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE INDEX "Watch_userId_idx" ON "Watch"("userId"); CREATE INDEX "Watch_isActive_idx" ON "Watch"("isActive"); CREATE INDEX "Snapshot_watchId_idx" ON "Snapshot"("watchId"); CREATE INDEX "Snapshot_watchId_capturedAt_idx" ON "Snapshot"("watchId", "capturedAt"); CREATE INDEX "Change_watchId_idx" ON "Change"("watchId"); CREATE INDEX "Change_detectedAt_idx" ON "Change"("detectedAt"); CREATE INDEX "Change_watchId_detectedAt_idx" ON "Change"("watchId", "detectedAt"); CREATE UNIQUE INDEX "UserInterest_userId_type_key" ON "UserInterest"("userId", "type"); CREATE INDEX "UserInterest_userId_idx" ON "UserInterest"("userId"); CREATE INDEX "Notification_userId_idx" ON "Notification"("userId"); CREATE INDEX "CheckRun_watchId_idx" ON "CheckRun"("watchId");
ALTER TABLE "Watch" ADD CONSTRAINT "Watch_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Snapshot" ADD CONSTRAINT "Snapshot_watchId_fkey" FOREIGN KEY ("watchId") REFERENCES "Watch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Change" ADD CONSTRAINT "Change_watchId_fkey" FOREIGN KEY ("watchId") REFERENCES "Watch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Change" ADD CONSTRAINT "Change_oldSnapshotId_fkey" FOREIGN KEY ("oldSnapshotId") REFERENCES "Snapshot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Change" ADD CONSTRAINT "Change_newSnapshotId_fkey" FOREIGN KEY ("newSnapshotId") REFERENCES "Snapshot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "UserInterest" ADD CONSTRAINT "UserInterest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_changeId_fkey" FOREIGN KEY ("changeId") REFERENCES "Change"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CheckRun" ADD CONSTRAINT "CheckRun_watchId_fkey" FOREIGN KEY ("watchId") REFERENCES "Watch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
-- Keep tables inaccessible through Supabase's Data API by default; NestJS enforces ownership through Prisma.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY; ALTER TABLE "Watch" ENABLE ROW LEVEL SECURITY; ALTER TABLE "Snapshot" ENABLE ROW LEVEL SECURITY; ALTER TABLE "Change" ENABLE ROW LEVEL SECURITY; ALTER TABLE "UserInterest" ENABLE ROW LEVEL SECURITY; ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY; ALTER TABLE "CheckRun" ENABLE ROW LEVEL SECURITY;
